### ISSUE TITLE
 place the "Check All" checkbox within the table header instead of outside the table?

### ISSUE THREAD

**Issue by zhyemqww** [yjg30737/pyqt-checkbox-table-widget#2]
like this
![image](https://github.com/yjg30737/pyqt-checkbox-table-widget/assets/89457830/4d4f03c9-c41f-4779-ac7b-5fa699e49e17)

**Comment by yjg30737** [comment]
I've actually tried it many times for a long time ago and failed it a lot.

I really wanna know how to do that too but don't think it's worth it

**Comment by zhyemqww** [comment]
I find a example https://github.com/SleepySoft/StockAnalysisSystem/blob/master/Demo/demo_header_check_qtableview_1.py， maybe it is useful.

**Comment by yjg30737** [comment]
![image](https://github.com/yjg30737/pyqt-checkbox-table-widget/assets/55078043/6e4f4a95-8c8c-452d-bafe-4b9ccaa12617)

Hmm. I think i partially remembered why i struggled with it. Because it looks unstable. One major difference of mine and that example is I actually managed to place checkbox on the center of it but for some reasons i didn't keep going on. I think the reason behind it is, as i remembered, checkbox covered the another cell's text, which is unstable. But that's old memory, so it can be inaccurate. I guess i'll give it a try to find my old source folder to figure out why i stopped that. If i find something useful i'll let you know. But not likely.
